version: '3'
networks:
  default:
services:
  keycloak:
    image: jboss/keycloak
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
    volumes:
      - ./keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - "8180:8080"